module.exports = {
    PARTICIPANT: "Participant",
    _50_POINT_GAMEWEEK: "50+ Point Gameweek",
    _75_POINT_GAMEWEEK: "75+ Point Gameweek",
    _100_POINT_GAMEWEEK: "100+ Point Gameweek",
    GAMEWEEK_WINNER: "Gameweek Winner",
    GAMEWEEK_LOSER: "Gameweek Loser",
    LEAGUE_LEADER: "League Leader",
    LEAGUE_LOSER: "League Loser",
    GAMEWEEK_MVP: "Gameweek MVP",
    NEGATIVE_GAMEWEEK_PLAYER: "Negative Gameweek Player",
    _15_POINT_GAMEWEEK_PLAYER: "15+ Point Gameweek Player",
    _20_POINT_GAMEWEEK_PLAYER: "20+ Point Gameweek Player",
    _25_POINT_GAMEWEEK_PLAYER: "25+ Point Gameweek Player",
    _10_POINT_BENCH_PLAYER: "10+ Point Bench Player",
    _15_GOAL_GAMEWEEK: "15+ Goal Gameweek",
    _10_GOAL_GAMEWEEK: "10+ Goal Gameweek",
    _5_GOAL_GAMEWEEK: "5+ Goal Gameweek",
    _0_GOAL_GAMEWEEK: "0 Goal Gameweek",
    _15_ASSIST_GAMEWEEK: "15+ Assist Gameweek",
    _10_ASSIST_GAMEWEEK: "10+ Assist Gameweek",
    _5_ASSIST_GAMEWEEK: "5+ Assist Gameweek",
    _0_ASSIST_GAMEWEEK: "0 Assist Gameweek"
};