version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "FPLWebsiteMobile"
s3_prefix = "FPLWebsiteMobile"
region = "us-east-1"
profile = "lotm"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "S3StaticWebsiteBucketNameParameter=\"thefiveblokes.com\" DomainNameParameter=\"thefiveblokes.com\" HostedZoneNameParameter=\"thefiveblokes.com.\""

